// ─── DATA ────────────────────────────────────────────────────────────────
// Edit freely. Add a company or school here and it appears on the map:
// pins are projected at runtime from `ll` = [longitude, latitude].
// region: "uk" | "eu" | "us" | "cr" | null (null = off every regional map)
// kind:   "f1" Formula 1 · "ls" launch & space · "ap" aerospace prime · "cr" Costa Rica
// feeders: [schoolId, strength, why]  strength 3 main pipeline · 2 regular · 1 nearby
// label:  preferred label side on the map: "r" | "l" | "t" | "b"

const UNIS = {
  // United Kingdom
  brookes:      { name: "Oxford Brookes University", short: "Oxford Brookes", city: "Oxford, UK", ll: [-1.2257, 51.7553], region: "uk", program: "BEng Mechanical Eng. (Motorsport) · strongest F1 alumni network" },
  cranfield:    { name: "Cranfield University", short: "Cranfield", city: "Bedfordshire, UK", ll: [-0.6286, 52.074], region: "uk", program: "MSc Advanced Motorsport Engineering (postgrad only)" },
  bath:         { name: "University of Bath", short: "Bath", city: "Bath, UK", ll: [-2.3271, 51.3797], region: "uk", program: "MEng with a 1-year industrial placement built into the degree" },
  southampton:  { name: "University of Southampton", short: "Southampton", city: "Southampton, UK", ll: [-1.3957, 50.9346], region: "uk", program: "Aero/astronautics + R.J. Mitchell wind tunnel" },
  imperial:     { name: "Imperial College London", short: "Imperial", city: "London, UK", ll: [-0.1749, 51.4988], region: "uk", program: "Mechanical / Electrical & Electronic Eng." },
  loughborough: { name: "Loughborough University", short: "Loughborough", city: "Loughborough, UK", ll: [-1.229, 52.765], region: "uk", program: "Automotive & mechatronics, sandwich placement year" },
  bristol:      { name: "University of Bristol", short: "Bristol", city: "Bristol, UK", ll: [-2.6023, 51.4585], region: "uk", program: "Aerospace / Mechanical Eng." },
  warwick:      { name: "University of Warwick", short: "Warwick", city: "Coventry, UK", ll: [-1.5615, 52.3793], region: "uk", program: "WMG: automotive electrification & batteries" },
  cambridge:    { name: "University of Cambridge", short: "Cambridge", city: "Cambridge, UK", ll: [0.1218, 52.2043], region: "uk", program: "General Engineering, specialise later · Whittle Lab (turbomachinery)" },
  surrey:       { name: "University of Surrey", short: "Surrey", city: "Guildford, UK", ll: [-0.5891, 51.2425], region: "uk", program: "Electrical/Mechanical Eng. with placement · 15 min from McLaren" },
  nottingham:   { name: "University of Nottingham", short: "Nottingham", city: "Nottingham, UK", ll: [-1.1953, 52.9387], region: "uk", program: "Mechanical / Electrical Eng. · Rolls-Royce University Technology Centres" },
  sheffield:    { name: "University of Sheffield", short: "Sheffield", city: "Sheffield, UK", ll: [-1.4884, 53.3811], region: "uk", program: "Aerospace / Mechanical Eng. · Advanced Manufacturing Research Centre (AMRC)" },

  // Continental Europe
  unimore:      { name: "Univ. di Modena e Reggio Emilia (MUNER)", short: "UNIMORE", city: "Modena, Italy", ll: [10.944, 44.6299], region: "eu", program: "MUNER Motorvehicle University, co-designed with Ferrari & the Motor Valley" },
  polimi:       { name: "Politecnico di Milano", short: "PoliMi", city: "Milan, Italy", ll: [9.2277, 45.4781], region: "eu", program: "Mechanical / Electrical / Aerospace Eng., English-taught MSc" },
  polito:       { name: "Politecnico di Torino", short: "PoliTo", city: "Turin, Italy", ll: [7.6597, 45.0628], region: "eu", program: "Automotive & Aerospace Engineering, mechatronics" },
  unibo:        { name: "Università di Bologna", short: "Bologna", city: "Bologna, Italy", ll: [11.3428, 44.4966], region: "eu", program: "Mechanical / Automation Eng. · MUNER partner · Forlì aerospace campus" },
  eth:          { name: "ETH Zürich", short: "ETH Zürich", city: "Zürich, Switzerland", ll: [8.5476, 47.3763], region: "eu", program: "Mechanical & Electrical Eng. · low tuition for internationals" },
  zhaw:         { name: "ZHAW", short: "ZHAW", city: "Winterthur, Switzerland", ll: [8.7292, 47.4979], region: "eu", program: "Applied sciences: systems & mechatronics, very hands-on" },
  tum:          { name: "TU München", short: "TU München", city: "Munich, Germany", ll: [11.6702, 48.265], region: "eu", program: "Mechanical / Electrical / Aerospace Eng. · near-zero tuition · WARR rocketry" },
  stuttgart:    { name: "Universität Stuttgart", short: "Stuttgart", city: "Stuttgart, Germany", ll: [9.105, 48.745], region: "eu", program: "Automotive & aerospace · vehicle institute (FKFS), space systems institute (IRS)" },
  isae:         { name: "ISAE-SUPAERO", short: "ISAE-SUPAERO", city: "Toulouse, France", ll: [1.4747, 43.5655], region: "eu", program: "Aerospace engineering · English-taught MSc in Aerospace Eng." },
  polytechnique:{ name: "École Polytechnique (IP Paris)", short: "Polytechnique", city: "Palaiseau, France", ll: [2.2115, 48.7133], region: "eu", program: "Engineering cycle + MSc · Paris-Saclay aerospace cluster" },
  tudelft:      { name: "TU Delft", short: "TU Delft", city: "Delft, Netherlands", ll: [4.3735, 51.999], region: "eu", program: "Aerospace Engineering · Delfi student-satellite program" },
  rwth:         { name: "RWTH Aachen", short: "RWTH Aachen", city: "Aachen, Germany", ll: [6.0659, 50.7779], region: "eu", program: "Mechanical / Electrical Eng. · one of Germany's largest engineering schools" },
  bremen:       { name: "Universität Bremen", short: "Bremen", city: "Bremen, Germany", ll: [8.8496, 53.1068], region: "eu", program: "Space engineering · ZARM drop tower" },
  thaugsburg:   { name: "Technische Hochschule Augsburg", short: "TH Augsburg", city: "Augsburg, Germany", ll: [10.901, 48.357], region: "eu", program: "Applied mechatronics & mechanical eng., practice-heavy" },

  // United States
  purdue:       { name: "Purdue University", short: "Purdue", city: "West Lafayette, IN", ll: [-86.9212, 40.4237], region: "us", program: "Aero/Astro, ME, ECE · 'Cradle of Astronauts' · Zucrow propulsion labs" },
  iui:          { name: "Indiana University Indianapolis", short: "IU Indianapolis", city: "Indianapolis, IN", ll: [-86.1752, 39.7743], region: "us", program: "BS Motorsports Engineering, rare in the US" },
  uncc:         { name: "UNC Charlotte", short: "UNC Charlotte", city: "Charlotte, NC", ll: [-80.7337, 35.3071], region: "us", program: "Mechanical Eng. with Motorsports concentration" },
  umich:        { name: "University of Michigan", short: "Michigan", city: "Ann Arbor, MI", ll: [-83.738, 42.278], region: "us", program: "Aerospace, ME, EE · MASA rocketry team" },
  gatech:       { name: "Georgia Tech", short: "Georgia Tech", city: "Atlanta, GA", ll: [-84.3963, 33.7756], region: "us", program: "Aerospace, ME, ECE · co-op program" },
  tamu:         { name: "Texas A&M University", short: "Texas A&M", city: "College Station, TX", ll: [-96.3344, 30.6187], region: "us", program: "Aerospace, ME, EE · big SpaceX alumni base" },
  utaustin:     { name: "UT Austin", short: "UT Austin", city: "Austin, TX", ll: [-97.7341, 30.2849], region: "us", program: "Aerospace, ME, ECE" },
  usc:          { name: "University of Southern California", short: "USC", city: "Los Angeles, CA", ll: [-118.2851, 34.0224], region: "us", program: "USC Rocket Propulsion Lab: student rocket reached space" },
  caltech:      { name: "Caltech", short: "Caltech", city: "Pasadena, CA", ll: [-118.1253, 34.1377], region: "us", program: "Small, elite; JPL next door" },
  uw:           { name: "University of Washington", short: "U. Washington", city: "Seattle, WA", ll: [-122.3035, 47.6553], region: "us", program: "Aeronautics & Astronautics, ME, EE" },
  erau:         { name: "Embry-Riddle Aeronautical Univ.", short: "Embry-Riddle", city: "Daytona Beach, FL", ll: [-81.0481, 29.1883], region: "us", program: "Aerospace / Mechanical Eng. · close to Cape Canaveral" },
  utrgv:        { name: "UT Rio Grande Valley", short: "UTRGV", city: "Brownsville, TX", ll: [-97.4889, 25.897], region: "us", program: "Mechanical / Electrical Eng. · 30 min from Starbase" },
  cuboulder:    { name: "University of Colorado Boulder", short: "CU Boulder", city: "Boulder, CO", ll: [-105.2659, 40.0076], region: "us", program: "Aerospace Engineering Sciences · at the center of Colorado's space industry" },
  mines:        { name: "Colorado School of Mines", short: "Mines", city: "Golden, CO", ll: [-105.2211, 39.751], region: "us", program: "Mechanical / Electrical Eng. · Space Resources program" },
  mit:          { name: "MIT", short: "MIT", city: "Cambridge, MA", ll: [-71.0942, 42.3601], region: "us", program: "Aero/Astro (Course 16), Mechanical, EECS" },
  stanford:     { name: "Stanford University", short: "Stanford", city: "Stanford, CA", ll: [-122.1697, 37.4275], region: "us", program: "Aero/Astro, ME, EE · Silicon Valley" },
  ucla:         { name: "UCLA", short: "UCLA", city: "Los Angeles, CA", ll: [-118.4452, 34.0689], region: "us", program: "Mechanical & Aerospace Eng. · Rocket Project at UCLA" },
  calpoly:      { name: "Cal Poly San Luis Obispo", short: "Cal Poly", city: "San Luis Obispo, CA", ll: [-120.6625, 35.305], region: "us", program: "Aerospace / Mechanical Eng. · co-created the CubeSat standard" },
  uiuc:         { name: "University of Illinois Urbana-Champaign", short: "UIUC", city: "Urbana, IL", ll: [-88.2272, 40.102], region: "us", program: "Aerospace, ME, ECE · one of the largest US engineering colleges" },
  vt:           { name: "Virginia Tech", short: "Virginia Tech", city: "Blacksburg, VA", ll: [-80.4227, 37.2284], region: "us", program: "Aerospace & Ocean Eng., ME, ECE" },
  umd:          { name: "University of Maryland", short: "Maryland", city: "College Park, MD", ll: [-76.9426, 38.9869], region: "us", program: "Aerospace Eng. · next door to NASA Goddard" },
  ucf:          { name: "University of Central Florida", short: "UCF", city: "Orlando, FL", ll: [-81.2001, 28.6024], region: "us", program: "Aerospace / Mechanical Eng. · near the Space Coast" },
  mst:          { name: "Missouri S&T", short: "Missouri S&T", city: "Rolla, MO", ll: [-91.7735, 37.9537], region: "us", program: "Aerospace / Mechanical Eng. · strong co-op culture" },
  auburn:       { name: "Auburn University", short: "Auburn", city: "Auburn, AL", ll: [-85.4808, 32.601], region: "us", program: "Aerospace / Mechanical Eng. · co-op program" },
  uah:          { name: "University of Alabama in Huntsville", short: "UAH", city: "Huntsville, AL", ll: [-86.6407, 34.7255], region: "us", program: "Aerospace / Mechanical Eng. · in 'Rocket City', next to NASA Marshall" },
  ucdavis:      { name: "UC Davis", short: "UC Davis", city: "Davis, CA", ll: [-121.7617, 38.5382], region: "us", program: "Mechanical & Aerospace Eng." },
  uconn:        { name: "University of Connecticut", short: "UConn", city: "Storrs, CT", ll: [-72.254, 41.8077], region: "us", program: "Mechanical / Electrical Eng. · Pratt & Whitney Additive Manufacturing Center" },
  rpi:          { name: "Rensselaer Polytechnic Institute", short: "RPI", city: "Troy, NY", ll: [-73.6788, 42.7298], region: "us", program: "Aeronautical / Mechanical Eng." },
  uh:           { name: "University of Houston", short: "U. Houston", city: "Houston, TX", ll: [-95.3422, 29.7199], region: "us", program: "Mechanical / Electrical Eng. · near NASA Johnson" },
  pennstate:    { name: "Penn State", short: "Penn State", city: "University Park, PA", ll: [-77.86, 40.7982], region: "us", program: "Aerospace / Mechanical Eng. · large recruiter base" },

  // Elsewhere
  auckland:     { name: "University of Auckland", short: "Auckland", city: "Auckland, NZ", ll: [174.77, -36.85], region: null, program: "Mechanical / Mechatronics Eng. · Rocket Lab's home city" },

  // Costa Rica
  tec:          { name: "Tecnológico de Costa Rica (TEC)", short: "TEC", city: "Cartago, CR", ll: [-83.9126, 9.8556], region: "cr", program: "Ing. Mecatrónica / Electromecánica · SETEC Lab (Irazú satellite)" },
  ucr:          { name: "Universidad de Costa Rica (UCR)", short: "UCR", city: "San Pedro, CR", ll: [-84.051, 9.937], region: "cr", program: "Ing. Eléctrica / Mecánica · Ad Astra research collaborations" }
};

const COMPANIES = [
  // ── Formula 1 ──
  { id: "redbull", name: "Red Bull Racing", kind: "f1", region: "uk", ll: [-0.7208, 52.0098], city: "Milton Keynes, UK", label: "r",
    angle: "Red Bull Powertrains builds its own 2026 hybrid power unit with Ford on site, so electromechanical work is core, not support.",
    feeders: [["brookes", 3, "Largest alumni presence on the factory floor"], ["cranfield", 3, "Motorsport MSc is a standard entry door; 15 km away"], ["bath", 2, "Placement-year students rotate through"], ["loughborough", 2, "Powertrain & mechatronics grads"]] },
  { id: "mercedes", name: "Mercedes-AMG", kind: "f1", region: "uk", ll: [-1.1407, 52.027], city: "Brackley, UK (engines: Brixworth)", label: "l",
    angle: "Mercedes HPP in Brixworth designs the power unit and energy-recovery system, the most electromechanical job in F1.",
    feeders: [["bath", 3, "Long-running industrial placement pipeline"], ["brookes", 3, "Deep alumni network, 40 min away"], ["cambridge", 2, "Graduate scheme intake"], ["loughborough", 2, "Powertrain engineering grads"]] },
  { id: "mclaren", name: "McLaren", kind: "f1", region: "uk", ll: [-0.541, 51.343], city: "Woking, UK", label: "r",
    angle: "Electronics heritage (former supplier of F1's standard ECU); controls and systems roles.",
    feeders: [["southampton", 3, "Aero & wind-tunnel heritage, close by"], ["imperial", 3, "London pipeline for systems & controls"], ["surrey", 2, "Neighbouring campus, placement year"], ["bath", 2, "Placement-year intake"]] },
  { id: "aston", name: "Aston Martin", kind: "f1", region: "uk", ll: [-1.018, 52.07], city: "Silverstone, UK", label: "t",
    angle: "Honda works power units from 2026: integrating electrical systems into the chassis is a growth area.",
    feeders: [["brookes", 3, "Primary local feeder"], ["cranfield", 3, "Motorsport MSc, 30 min away"], ["warwick", 2, "WMG electrification expertise"], ["loughborough", 2, "Automotive grads"]] },
  { id: "williams", name: "Williams", kind: "f1", region: "uk", ll: [-1.42, 51.611], city: "Grove, UK", label: "b",
    angle: "Battery and hybrid know-how from its former advanced-engineering arm; chassis-side energy-recovery integration.",
    feeders: [["brookes", 3, "20 min away, heavy alumni presence"], ["bath", 3, "Placement-year pipeline"], ["southampton", 2, "Aero recruits"]] },
  { id: "alpine", name: "Alpine", kind: "f1", region: "uk", ll: [-1.4508, 51.923], city: "Enstone, UK", label: "l",
    angle: "Customer Mercedes power units from 2026: electromech roles shift to integration and vehicle systems.",
    feeders: [["brookes", 3, "Closest major feeder"], ["bath", 2, "Placements"], ["bristol", 2, "Aero & mechanical grads"], ["cranfield", 2, "Motorsport MSc"]] },
  { id: "ferrari", name: "Ferrari", kind: "f1", region: "eu", ll: [10.8656, 44.532], city: "Maranello, Italy", label: "b",
    angle: "Designs and builds its own power unit in Maranello: the full electromechanical stack under one roof.",
    feeders: [["unimore", 3, "MUNER was built with Ferrari; 15 km away"], ["polimi", 3, "Top Italian engineering feeder"], ["polito", 2, "Automotive engineering tradition"], ["unibo", 2, "MUNER partner"]] },
  { id: "rb", name: "Racing Bulls", kind: "f1", region: "eu", ll: [11.877, 44.29], city: "Faenza, Italy", label: "r",
    angle: "Smaller team: engineers touch more systems early, a fast learning curve.",
    feeders: [["unibo", 3, "Regional feeder, MUNER partner"], ["unimore", 2, "Motor Valley pipeline"], ["polimi", 2, "Graduate intake"]] },
  { id: "audi", name: "Audi F1", kind: "f1", region: "eu", ll: [8.843, 47.297], city: "Hinwil, Switzerland (engines: Neuburg, DE)", label: "r",
    angle: "Brand-new works hybrid power unit from Neuburg, hiring electromech talent from scratch.",
    feeders: [["eth", 3, "20 km away; Zürich talent pool"], ["tum", 3, "Audi/Bavarian engineering pipeline"], ["zhaw", 2, "Applied mechatronics, very practical"], ["stuttgart", 2, "Powertrain institute"]] },
  { id: "haas", name: "Haas", kind: "f1", region: "us", ll: [-80.6217, 35.4874], city: "Kannapolis, NC (also Banbury, UK)", label: "r",
    angle: "Lean team built on Ferrari parts; NASCAR country gives a strong local motorsport labour market.",
    feeders: [["uncc", 3, "Motorsports concentration, 30 min away"], ["brookes", 2, "Feeds the Banbury UK base"], ["purdue", 1, "Engineering intake"]] },
  { id: "cadillac", name: "Cadillac", kind: "f1", region: "us", ll: [-86.013, 39.9568], city: "Fishers, IN (also Silverstone & Charlotte)", label: "r",
    angle: "GM is building its own F1 power unit for later this decade: a new electromech program starting now.",
    feeders: [["purdue", 3, "Largest Indiana engineering school, 1 hr away"], ["iui", 3, "Motorsports Engineering BS, 25 min away"], ["umich", 2, "GM's engineering home turf"], ["uncc", 2, "Feeds the Charlotte engine site"]] },

  // ── Launch & space ──
  { id: "spacex", name: "SpaceX", kind: "ls", region: "us", ll: [-97.157, 25.997], city: "Starbase, TX (also Hawthorne, CA)", label: "r",
    angle: "Avionics, engine controls, actuators and power systems: electromechanical work is everywhere on Starship.",
    feeders: [["purdue", 3, "Top propulsion feeder; Zucrow labs"], ["umich", 3, "Consistently a top SpaceX source"], ["tamu", 3, "Large SpaceX alumni base, in-state"], ["gatech", 2, "Co-op pipeline"], ["usc", 2, "Rocketry team recruits for Hawthorne"], ["utrgv", 1, "Local campus near Starbase"]] },
  { id: "blue", name: "Blue Origin", kind: "ls", region: "us", ll: [-122.2348, 47.3809], city: "Kent, WA (also Cape Canaveral & Huntsville)", label: "l",
    angle: "BE-4 engines, New Glenn and the Blue Moon lander: propulsion controls and power systems.",
    feeders: [["uw", 3, "Next door; largest local feeder"], ["purdue", 2, "Propulsion grads"], ["umich", 2, "Aero grads"], ["erau", 2, "Florida launch operations"], ["ucf", 2, "New Glenn factory on the Space Coast"]] },
  { id: "rocketlab", name: "Rocket Lab", kind: "ls", region: "us", ll: [-118.1937, 33.7701], city: "Long Beach, CA (also Auckland, NZ)", label: "b",
    angle: "Small launchers, satellites and spacecraft parts: reaction wheels, solar arrays and avionics are all electromechanical.",
    feeders: [["usc", 3, "Rocketry lab 30 min away"], ["caltech", 2, "Elite but small"], ["auckland", 2, "Feeds the NZ headquarters"]] },
  { id: "relativity", name: "Relativity Space", kind: "ls", region: "us", ll: [-118.144, 33.829], city: "Long Beach, CA", label: "r",
    angle: "Terran R reusable rocket built in a heavily automated factory: robotics and test-stand controls sit next to the rocket.",
    feeders: [["usc", 3, "Rocket Propulsion Lab alumni, 30 min away"], ["ucla", 3, "Rocket Project team, same metro area"], ["calpoly", 2, "Hands-on aerospace grads"], ["purdue", 2, "Propulsion grads"]] },
  { id: "firefly", name: "Firefly Aerospace", kind: "ls", region: "us", ll: [-97.8203, 30.5052], city: "Cedar Park, TX", label: "l",
    angle: "Alpha rocket and the Blue Ghost lunar lander, which landed on the Moon in 2025: GNC, avionics and landing systems.",
    feeders: [["utaustin", 3, "30 min away"], ["tamu", 3, "In-state aerospace pipeline"], ["purdue", 1, "Propulsion grads"]] },
  { id: "stoke", name: "Stoke Space", kind: "ls", region: "us", ll: [-122.262, 47.418], city: "Kent, WA", label: "r",
    angle: "Nova, a fully reusable rocket: a small team where one engineer covers hardware, wiring and test.",
    feeders: [["uw", 3, "Local aero/astro pipeline"], ["purdue", 2, "Propulsion grads"], ["umich", 1, "Aero grads"]] },
  { id: "sierra", name: "Sierra Space", kind: "ls", region: "us", ll: [-105.1319, 39.9778], city: "Louisville, CO (also Space Coast, FL)", label: "r",
    angle: "Dream Chaser spaceplane and inflatable habitats: power, thermal and mechanism design.",
    feeders: [["cuboulder", 3, "15 min away"], ["mines", 2, "Colorado engineering pipeline"], ["erau", 2, "Florida operations near KSC"]] },
  { id: "intuitive", name: "Intuitive Machines", kind: "ls", region: "us", ll: [-95.165, 29.607], city: "Houston, TX", label: "b",
    angle: "Nova-C lunar landers; in 2024 it made the first commercial Moon landing. Landing engines, sensors and power.",
    feeders: [["uh", 3, "Local feeder, near NASA Johnson"], ["tamu", 3, "In-state aerospace pipeline"], ["utaustin", 2, "Aerospace grads"]] },
  { id: "ula", name: "United Launch Alliance", kind: "ls", region: "us", ll: [-104.8697, 39.5807], city: "Centennial, CO (factory: Decatur, AL)", label: "r",
    angle: "Vulcan Centaur: avionics, engine controls and ground systems, built in Decatur, Alabama.",
    feeders: [["cuboulder", 3, "Colorado HQ talent pool"], ["uah", 3, "Huntsville, 30 min from the Decatur factory"], ["mines", 2, "Colorado engineering pipeline"], ["auburn", 2, "Alabama co-op pipeline"]] },
  { id: "ariane", name: "ArianeGroup", kind: "ls", region: "eu", ll: [1.9119, 48.99], city: "Les Mureaux, France (also Vernon & Bremen)", label: "r",
    angle: "Ariane 6: engines in Vernon, stage integration in Les Mureaux, the upper stage in Bremen.",
    feeders: [["isae", 3, "France's aerospace grande école"], ["polytechnique", 3, "Paris-region engineering elite"], ["bremen", 2, "Feeds the Bremen upper-stage site"], ["rwth", 1, "German engineering intake"]] },
  { id: "isar", name: "Isar Aerospace", kind: "ls", region: "eu", ll: [11.665, 48.064], city: "Ottobrunn, Germany", label: "r",
    angle: "Spectrum launcher, first flown from Andøya in 2025. Founded by TUM alumni; engines, avionics and test are in-house.",
    feeders: [["tum", 3, "Founders came from TUM; WARR rocketry pipeline"], ["stuttgart", 2, "Space systems institute"], ["eth", 1, "Swiss engineering intake"]] },
  { id: "rfa", name: "Rocket Factory Augsburg", kind: "ls", region: "eu", ll: [10.87, 48.39], city: "Augsburg, Germany", label: "l",
    angle: "RFA One launcher, part of the OHB group; staged-combustion engines developed and tested in-house.",
    feeders: [["thaugsburg", 3, "Local applied-sciences feeder"], ["tum", 2, "Munich engineering pipeline"], ["stuttgart", 2, "Space systems institute"]] },

  // ── Aerospace primes ──
  { id: "boeing", name: "Boeing", kind: "ap", region: "us", ll: [-122.275, 47.922], city: "Everett, WA (also St. Louis; HQ Arlington, VA)", label: "r",
    angle: "Fly-by-wire actuation, the 'more-electric' 787, Starliner and the SLS core stage: systems integration at huge scale.",
    feeders: [["uw", 3, "Largest Seattle-area feeder"], ["erau", 3, "Aviation-focused pipeline"], ["purdue", 2, "Large Boeing alumni base"], ["uiuc", 2, "Midwest engineering pipeline"], ["mst", 2, "Feeds Boeing Defense in St. Louis"], ["gatech", 2, "Co-op pipeline"]] },
  { id: "lockheed", name: "Lockheed Martin", kind: "ap", region: "us", ll: [-105.1072, 39.497], city: "Littleton, CO (also Sunnyvale, Fort Worth, Orlando)", label: "l",
    angle: "Orion spacecraft, GPS III satellites and missile programs: avionics, power and actuation across space and defense.",
    feeders: [["cuboulder", 3, "Next to the Space HQ"], ["erau", 3, "Long-running recruiting pipeline"], ["mines", 2, "Colorado engineering pipeline"], ["purdue", 2, "Aero/Astro grads"], ["ucf", 2, "Feeds the Orlando site"], ["stanford", 1, "Feeds the Sunnyvale space site"]] },
  { id: "northrop", name: "Northrop Grumman", kind: "ap", region: "us", ll: [-77.448, 38.953], city: "Dulles, VA (also Redondo Beach, CA)", label: "r",
    angle: "Built the James Webb Space Telescope; Cygnus cargo, satellites and solid rocket motors. Deployable mechanisms and power systems.",
    feeders: [["vt", 3, "In-state aerospace pipeline"], ["umd", 3, "Washington-area feeder"], ["pennstate", 2, "Aerospace/ME grads"], ["gatech", 2, "Co-op pipeline"], ["purdue", 2, "Aero/Astro grads"]] },
  { id: "aerojet", name: "L3Harris Aerojet Rocketdyne", kind: "ap", region: "us", ll: [-121.237, 38.601], city: "Rancho Cordova, CA (also Canoga Park & Huntsville)", label: "r",
    angle: "RS-25 engines for SLS, RL10 upper-stage engines and electric (Hall-effect) thrusters.",
    feeders: [["ucdavis", 3, "20 min from the Sacramento site"], ["calpoly", 2, "Hands-on propulsion grads"], ["purdue", 2, "Propulsion grads"], ["uah", 2, "Feeds the Huntsville site"]] },
  { id: "pw", name: "Pratt & Whitney", kind: "ap", region: "us", ll: [-72.622, 41.76], city: "East Hartford, CT", label: "b",
    angle: "Geared turbofans and the F-35's F135 engine: full-authority engine controls and hybrid-electric demonstrators.",
    feeders: [["uconn", 3, "In-state partner; additive manufacturing center"], ["rpi", 3, "Long-running New England pipeline"], ["mit", 2, "Gas Turbine Lab heritage"], ["purdue", 1, "Propulsion grads"]] },
  { id: "airbus", name: "Airbus", kind: "ap", region: "eu", ll: [1.364, 43.629], city: "Toulouse, France (also Hamburg, Bremen, Filton & Stevenage)", label: "l",
    angle: "Fly-by-wire pioneer. Airbus Defence and Space builds satellites in Toulouse and Stevenage, and Orion's European Service Module in Bremen.",
    feeders: [["isae", 3, "Next door in Toulouse"], ["tudelft", 2, "Aerospace Engineering grads"], ["tum", 2, "Feeds the Munich-area space sites"], ["polytechnique", 2, "French engineering elite"], ["bristol", 2, "Airbus wing design at Filton, Bristol"]] },
  { id: "thales", name: "Thales Alenia Space", kind: "ap", region: "eu", ll: [7.61, 45.087], city: "Turin, Italy (also Rome & Cannes)", label: "t",
    angle: "Pressurised modules for the ISS, Lunar Gateway and Axiom: Turin builds many of the habitats people live in off Earth.",
    feeders: [["polito", 3, "Same city; aerospace engineering"], ["polimi", 2, "Aerospace grads"], ["unibo", 1, "Forlì aerospace campus"]] },
  { id: "rollsroyce", name: "Rolls-Royce", kind: "ap", region: "uk", ll: [-1.443, 52.901], city: "Derby, UK", label: "l",
    angle: "Trent aero engines and electrical power systems; UltraFan and hybrid-electric research.",
    feeders: [["nottingham", 3, "Rolls-Royce University Technology Centres"], ["loughborough", 3, "Combustion research centre, 25 min away"], ["sheffield", 2, "AMRC manufacturing partner"], ["cambridge", 2, "Whittle Lab turbomachinery"], ["imperial", 2, "Engineering intake"]] },

  // ── Costa Rica ──
  { id: "adastra", name: "Ad Astra Rocket Co.", kind: "cr", region: "cr", ll: [-85.437, 10.634], city: "Liberia, Guanacaste, CR", label: "r",
    angle: "Franklin Chang Díaz's VASIMR plasma engine: power electronics and electromagnetics, a rocket engine in Costa Rica.",
    feeders: [["tec", 3, "Core local feeder; Cartago"], ["ucr", 3, "Research collaboration"]] }
];
